export const HOMEPAGE_CASE_STUDY_SLUGS = [
  "desarmadero-operations-prototype",
  "genrupt",
  "acquire",
  "palabruno",
] as const;

export const PROJECT_INDEX_ORDER = [
  "palabruno",
  "acquire",
  "job-application-assistant",
  "genrupt",
  "casamo",
  "desarmadero-operations-prototype",
  "linkedin-tools",
  "codex-telegram-bridge",
  "agent-recall",
  "client-feedback",
  "online-store-conversion-review",
  "health-ai-search-audit",
  "apartment-finder",
  "ba-eventos",
  "language-exchange",
  "mucho-hangouts",
  "casa-elaria",
  "desarmadero-latorre",
  "maximo-interiorismo",
  "redwriter-comics",
  "vox-prismatic",
] as const;
